apiVersion: v1
kind: Service
metadata:
  name: fil-rouge-api
  namespace: fil-rouge
spec:
  type: NodePort
  selector:
    app: fil-rouge-api
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
